return {
	disc_ep01_command_expedition_terminal = {
		DiscoveryId = "disc_ep01_command_expedition_terminal",
		ZoneId = "zone_ep01_command_center",
		ExplorerScore = 10,
		RewardBundleId = "reward_ep01_main_001",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_expedition_started" },
	},
	disc_ep01_command_star_core_display = {
		DiscoveryId = "disc_ep01_command_star_core_display",
		ZoneId = "zone_ep01_command_center",
		ExplorerScore = 15,
		RewardBundleId = "reward_ep01_main_001",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_star_core_segment_status" },
	},
	disc_ep01_universe_first_signal_marker = {
		DiscoveryId = "disc_ep01_universe_first_signal_marker",
		ZoneId = "zone_ep01_universe_explorer",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_002",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_broken_star_signal" },
	},
	disc_ep01_universe_analysis_station = {
		DiscoveryId = "disc_ep01_universe_analysis_station",
		ZoneId = "zone_ep01_universe_explorer",
		ExplorerScore = 10,
		RewardBundleId = "reward_ep01_main_002",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_universe_puzzle_station = {
		DiscoveryId = "disc_ep01_universe_puzzle_station",
		ZoneId = "zone_ep01_universe_explorer",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_003",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_universe_fragment = {
		DiscoveryId = "disc_ep01_universe_fragment",
		ZoneId = "zone_ep01_universe_explorer",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_003",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_fragment_universe" },
	},
	disc_ep01_terrain_flow_console = {
		DiscoveryId = "disc_ep01_terrain_flow_console",
		ZoneId = "zone_ep01_terrain_sandbox",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_004",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_terrain_fragment = {
		DiscoveryId = "disc_ep01_terrain_fragment",
		ZoneId = "zone_ep01_terrain_sandbox",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_004",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_fragment_earth" },
	},
	disc_ep01_terrain_observation_point = {
		DiscoveryId = "disc_ep01_terrain_observation_point",
		ZoneId = "zone_ep01_terrain_sandbox",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_004",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_theos_calibration_console = {
		DiscoveryId = "disc_ep01_theos_calibration_console",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_005",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = { "lore_ep01_theos_calibration_console" },
		JournalUnlockIds = {},
	},
	disc_ep01_theos_fragment = {
		DiscoveryId = "disc_ep01_theos_fragment",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_005",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = { "lore_ep01_theos_fragment" },
		JournalUnlockIds = { "journal_ep01_fragment_theos" },
	},
	disc_ep01_theos_satellite_history = {
		DiscoveryId = "disc_ep01_theos_satellite_history",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_discovery_theos_satellite_history",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = { "lore_ep01_theos_satellite_history" },
		JournalUnlockIds = { "journal_ep01_theos_satellite_history" },
	},
	disc_ep01_theos_theos_1 = {
		DiscoveryId = "disc_ep01_theos_theos_1",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_discovery_theos_theos_1",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = { "lore_ep01_theos_theos_1" },
		JournalUnlockIds = { "journal_ep01_theos_theos_1" },
	},
	disc_ep01_theos_theos_2 = {
		DiscoveryId = "disc_ep01_theos_theos_2",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_discovery_theos_theos_2",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = { "lore_ep01_theos_theos_2" },
		JournalUnlockIds = { "journal_ep01_theos_theos_2" },
	},
	disc_ep01_theos_thailand_map = {
		DiscoveryId = "disc_ep01_theos_thailand_map",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_discovery_theos_thailand_map",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = { "lore_ep01_theos_thailand_map" },
		JournalUnlockIds = { "journal_ep01_theos_thailand_map" },
	},
	disc_ep01_theos_satellite_imagery = {
		DiscoveryId = "disc_ep01_theos_satellite_imagery",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_optional_005_satellite_imagery",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = { "lore_ep01_theos_satellite_imagery" },
		JournalUnlockIds = { "journal_ep01_theos_satellite_imagery" },
	},
	disc_ep01_theos_disaster_monitoring = {
		DiscoveryId = "disc_ep01_theos_disaster_monitoring",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_optional_005_flood_monitoring",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = { "lore_ep01_theos_disaster_monitoring" },
		JournalUnlockIds = { "journal_ep01_theos_flood_monitoring" },
	},
	disc_ep01_theos_agriculture_monitoring = {
		DiscoveryId = "disc_ep01_theos_agriculture_monitoring",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_optional_005_agriculture_monitoring",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = { "lore_ep01_theos_agriculture_monitoring" },
		JournalUnlockIds = { "journal_ep01_theos_agriculture_monitoring" },
	},
	disc_ep01_theos_water_resource_monitoring = {
		DiscoveryId = "disc_ep01_theos_water_resource_monitoring",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_discovery_theos_water_resource_monitoring",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = { "lore_ep01_theos_water_resource_monitoring" },
		JournalUnlockIds = { "journal_ep01_theos_water_resource_monitoring" },
	},
	disc_ep01_theos_forest_monitoring = {
		DiscoveryId = "disc_ep01_theos_forest_monitoring",
		ZoneId = "zone_ep01_theos_satellite_center",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_discovery_theos_forest_monitoring",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = { "lore_ep01_theos_forest_monitoring" },
		JournalUnlockIds = { "journal_ep01_theos_forest_monitoring" },
	},
	disc_ep01_rocket_preflight_console = {
		DiscoveryId = "disc_ep01_rocket_preflight_console",
		ZoneId = "zone_ep01_rocket_mission",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_006",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_rocket_launch_platform = {
		DiscoveryId = "disc_ep01_rocket_launch_platform",
		ZoneId = "zone_ep01_rocket_mission",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_006",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_rocket_fragment = {
		DiscoveryId = "disc_ep01_rocket_fragment",
		ZoneId = "zone_ep01_rocket_mission",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_006",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_fragment_rocket" },
	},
	disc_ep01_astronaut_training_entry = {
		DiscoveryId = "disc_ep01_astronaut_training_entry",
		ZoneId = "zone_ep01_astronaut_training",
		ExplorerScore = 10,
		RewardBundleId = "reward_ep01_main_007",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_astronaut_readiness_station = {
		DiscoveryId = "disc_ep01_astronaut_readiness_station",
		ZoneId = "zone_ep01_astronaut_training",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_007",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_astronaut_readiness" },
	},
	disc_ep01_astronaut_badge_terminal = {
		DiscoveryId = "disc_ep01_astronaut_badge_terminal",
		ZoneId = "zone_ep01_astronaut_training",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_007",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_moon_walk_entry = {
		DiscoveryId = "disc_ep01_moon_walk_entry",
		ZoneId = "zone_ep01_moon_walk",
		ExplorerScore = 10,
		RewardBundleId = "reward_ep01_main_008",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_moon_low_gravity_route = {
		DiscoveryId = "disc_ep01_moon_low_gravity_route",
		ZoneId = "zone_ep01_moon_walk",
		ExplorerScore = 25,
		RewardBundleId = "reward_ep01_main_008",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = {},
	},
	disc_ep01_moon_fragment = {
		DiscoveryId = "disc_ep01_moon_fragment",
		ZoneId = "zone_ep01_moon_walk",
		ExplorerScore = 50,
		RewardBundleId = "reward_ep01_main_008",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_fragment_moon" },
	},
	disc_ep01_moon_star_core_segment_restoration_point = {
		DiscoveryId = "disc_ep01_moon_star_core_segment_restoration_point",
		ZoneId = "zone_ep01_moon_walk",
		ExplorerScore = 50,
		RewardBundleId = "reward_ep01_main_008",
		RewardIncludedInQuestBundle = true,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_star_core_segment_01_restored" },
	},
	disc_ep01_hidden_space_inspirium_secret = {
		DiscoveryId = "disc_ep01_hidden_space_inspirium_secret",
		ZoneId = "zone_ep01_command_center",
		ExplorerScore = 100,
		RewardBundleId = "reward_ep01_hidden_space_inspirium_secret",
		RewardIncludedInQuestBundle = false,
		LoreUnlockIds = {},
		JournalUnlockIds = { "journal_ep01_hidden_space_inspirium_secret" },
	},
}
