return {
	interaction_npc_atom_guide = {
		InteractionId = "interaction_npc_atom_guide",
		Type = "NPCGuide",
		VisibilityPolicy = "NPCGuide",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Ask",
		PromptObjectText = "Atom",
		CharacterId = "character_atom",
	},
	interaction_npc_neutron_guide = {
		InteractionId = "interaction_npc_neutron_guide",
		Type = "NPCGuide",
		VisibilityPolicy = "NPCGuide",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Ask",
		PromptObjectText = "Neutron",
		CharacterId = "character_neutron",
	},
	interaction_npc_proton_guide = {
		InteractionId = "interaction_npc_proton_guide",
		Type = "NPCGuide",
		VisibilityPolicy = "NPCGuide",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Ask",
		PromptObjectText = "Proton",
		CharacterId = "character_proton",
	},
	interaction_start_ep01_main_001 = {
		InteractionId = "interaction_start_ep01_main_001",
		Type = "QuestStart",
		VisibilityPolicy = "QuestStart",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Start Quest",
		PromptObjectText = "Expedition Launch",
		QuestId = "quest_ep01_main_001",
	},
	interaction_start_ep01_main_002 = {
		InteractionId = "interaction_start_ep01_main_002",
		Type = "QuestStart",
		VisibilityPolicy = "QuestStart",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Start Quest",
		PromptObjectText = "Universe Signal Mission",
		QuestId = "quest_ep01_main_002",
	},
	interaction_start_ep01_main_003 = {
		InteractionId = "interaction_start_ep01_main_003",
		Type = "QuestStart",
		VisibilityPolicy = "QuestStart",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Start Quest",
		PromptObjectText = "Quest 003",
		QuestId = "quest_ep01_main_003",
	},
	interaction_start_ep01_main_004 = {
		InteractionId = "interaction_start_ep01_main_004",
		Type = "QuestStart",
		VisibilityPolicy = "QuestStart",
		ZoneId = "zone_ep01_terrain_sandbox",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Start Quest",
		PromptObjectText = "Quest 004",
		QuestId = "quest_ep01_main_004",
	},
	interaction_complete_ep01_main_001 = {
		InteractionId = "interaction_complete_ep01_main_001",
		Type = "QuestComplete",
		VisibilityPolicy = "QuestComplete",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Complete Quest",
		PromptObjectText = "Complete Quest 001",
		QuestId = "quest_ep01_main_001",
	},
	interaction_complete_ep01_main_002 = {
		InteractionId = "interaction_complete_ep01_main_002",
		Type = "QuestComplete",
		VisibilityPolicy = "QuestComplete",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Complete Quest",
		PromptObjectText = "Complete Quest 002",
		QuestId = "quest_ep01_main_002",
	},
	interaction_complete_ep01_main_003 = {
		InteractionId = "interaction_complete_ep01_main_003",
		Type = "QuestComplete",
		VisibilityPolicy = "QuestComplete",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Complete Quest",
		PromptObjectText = "Complete Quest 003",
		QuestId = "quest_ep01_main_003",
	},
	interaction_complete_ep01_main_004 = {
		InteractionId = "interaction_complete_ep01_main_004",
		Type = "QuestComplete",
		VisibilityPolicy = "QuestComplete",
		ZoneId = "zone_ep01_terrain_sandbox",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Complete Quest",
		PromptObjectText = "Complete Quest 004",
		QuestId = "quest_ep01_main_004",
	},
	interaction_ep01_main_001_001 = {
		InteractionId = "interaction_ep01_main_001_001",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Expedition Terminal",
		QuestId = "quest_ep01_main_001",
		ObjectiveId = "obj_ep01_main_001_001",
	},
	interaction_ep01_main_001_002 = {
		InteractionId = "interaction_ep01_main_001_002",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Mission Briefing",
		QuestId = "quest_ep01_main_001",
		ObjectiveId = "obj_ep01_main_001_002",
	},
	interaction_ep01_main_001_003 = {
		InteractionId = "interaction_ep01_main_001_003",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Launch Console",
		QuestId = "quest_ep01_main_001",
		ObjectiveId = "obj_ep01_main_001_003",
	},
	interaction_ep01_main_002_002 = {
		InteractionId = "interaction_ep01_main_002_002",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Locate",
		PromptObjectText = "First Signal Marker",
		QuestId = "quest_ep01_main_002",
		ObjectiveId = "obj_ep01_main_002_002",
	},
	interaction_ep01_main_002_001 = {
		InteractionId = "interaction_ep01_main_002_001",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Enter Zone",
		PromptObjectText = "Enter Universe Explorer",
		QuestId = "quest_ep01_main_002",
		ObjectiveId = "obj_ep01_main_002_001",
	},
	interaction_ep01_main_002_003 = {
		InteractionId = "interaction_ep01_main_002_003",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Scan",
		PromptObjectText = "Signal Marker",
		QuestId = "quest_ep01_main_002",
		ObjectiveId = "obj_ep01_main_002_003",
	},
	interaction_ep01_main_002_004 = {
		InteractionId = "interaction_ep01_main_002_004",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Analyze",
		PromptObjectText = "Neutron Analysis Station",
		QuestId = "quest_ep01_main_002",
		ObjectiveId = "obj_ep01_main_002_004",
	},
	interaction_ep01_main_003_001 = {
		InteractionId = "interaction_ep01_main_003_001",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Follow",
		PromptObjectText = "Star Signal Trail",
		QuestId = "quest_ep01_main_003",
		ObjectiveId = "obj_ep01_main_003_001",
	},
	interaction_ep01_main_003_002 = {
		InteractionId = "interaction_ep01_main_003_002",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Inspect",
		PromptObjectText = "Unstable Signal Echo",
		QuestId = "quest_ep01_main_003",
		ObjectiveId = "obj_ep01_main_003_002",
	},
	interaction_ep01_main_003_003 = {
		InteractionId = "interaction_ep01_main_003_003",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Stabilize",
		PromptObjectText = "Universe Fragment",
		QuestId = "quest_ep01_main_003",
		ObjectiveId = "obj_ep01_main_003_003",
	},
	interaction_ep01_main_003_004 = {
		InteractionId = "interaction_ep01_main_003_004",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Recover",
		PromptObjectText = "Universe Fragment",
		QuestId = "quest_ep01_main_003",
		ObjectiveId = "obj_ep01_main_003_004",
	},
	interaction_ep01_main_004_001 = {
		InteractionId = "interaction_ep01_main_004_001",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_terrain_sandbox",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Enter",
		PromptObjectText = "Terrain Sandbox",
		QuestId = "quest_ep01_main_004",
		ObjectiveId = "obj_ep01_main_004_001",
	},
	interaction_ep01_main_004_002 = {
		InteractionId = "interaction_ep01_main_004_002",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_terrain_sandbox",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Find",
		PromptObjectText = "Earth Memory Marker",
		QuestId = "quest_ep01_main_004",
		ObjectiveId = "obj_ep01_main_004_002",
	},
	interaction_ep01_main_004_003 = {
		InteractionId = "interaction_ep01_main_004_003",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_terrain_sandbox",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Rebuild",
		PromptObjectText = "Terrain Memory Path",
		QuestId = "quest_ep01_main_004",
		ObjectiveId = "obj_ep01_main_004_003",
	},
	interaction_ep01_main_004_004 = {
		InteractionId = "interaction_ep01_main_004_004",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_terrain_sandbox",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Recover",
		PromptObjectText = "Earth Fragment",
		QuestId = "quest_ep01_main_004",
		ObjectiveId = "obj_ep01_main_004_004",
	},
	interaction_ep01_main_005_003 = {
		InteractionId = "interaction_ep01_main_005_003",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_theos_satellite_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "THEOS Monitor",
		QuestId = "quest_ep01_main_005",
		ObjectiveId = "obj_ep01_main_005_003",
	},
	interaction_ep01_main_008_005 = {
		InteractionId = "interaction_ep01_main_008_005",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_moon_walk",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Star Core Restoration Point",
		QuestId = "quest_ep01_main_008",
		ObjectiveId = "obj_ep01_main_008_005",
	},
	interaction_disc_ep01_command_star_core_display = {
		InteractionId = "interaction_disc_ep01_command_star_core_display",
		Type = "Discovery",
		VisibilityPolicy = "Discovery",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Inspect",
		PromptObjectText = "Star Core Display",
		DiscoveryId = "disc_ep01_command_star_core_display",
		ObjectiveProgressIds = {
			"obj_ep01_main_001_004",
		},
	},
	interaction_disc_ep01_universe_first_signal_marker = {
		InteractionId = "interaction_disc_ep01_universe_first_signal_marker",
		Type = "Discovery",
		VisibilityPolicy = "Discovery",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = false,
		PromptActionText = "Inspect",
		PromptObjectText = "First Signal Marker",
		DiscoveryId = "disc_ep01_universe_first_signal_marker",
		ObjectiveProgressIds = {
			"obj_ep01_main_002_002",
		},
	},
	interaction_disc_ep01_universe_analysis_station = {
		InteractionId = "interaction_disc_ep01_universe_analysis_station",
		Type = "Discovery",
		VisibilityPolicy = "Discovery",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = false,
		PromptActionText = "Inspect",
		PromptObjectText = "Neutron Analysis Station",
		DiscoveryId = "disc_ep01_universe_analysis_station",
		ObjectiveProgressIds = {
			"obj_ep01_main_002_004",
		},
	},
	interaction_travel_ep01_universe_explorer = {
		InteractionId = "interaction_travel_ep01_universe_explorer",
		Type = "ZoneTravel",
		VisibilityPolicy = "ZoneTravel",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Travel",
		PromptObjectText = "Universe Explorer",
	},
}
