return {
	interaction_ep01_main_001_001 = {
		InteractionId = "interaction_ep01_main_001_001",
		Type = "QuestObjective",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Expedition Terminal",
		QuestId = "quest_ep01_main_001",
		ObjectiveId = "obj_ep01_main_001_001",
	},
	interaction_ep01_main_001_002 = {
		InteractionId = "interaction_ep01_main_001_002",
		Type = "QuestObjective",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Mission Briefing",
		QuestId = "quest_ep01_main_001",
		ObjectiveId = "obj_ep01_main_001_002",
	},
	interaction_ep01_main_001_003 = {
		InteractionId = "interaction_ep01_main_001_003",
		Type = "QuestObjective",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Launch Console",
		QuestId = "quest_ep01_main_001",
		ObjectiveId = "obj_ep01_main_001_003",
	},
	interaction_ep01_main_002_002 = {
		InteractionId = "interaction_ep01_main_002_002",
		Type = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Signal Marker",
		QuestId = "quest_ep01_main_002",
		ObjectiveId = "obj_ep01_main_002_002",
	},
	interaction_ep01_main_005_003 = {
		InteractionId = "interaction_ep01_main_005_003",
		Type = "QuestObjective",
		ZoneId = "zone_ep01_theos_satellite_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "THEOS Monitor",
		QuestId = "quest_ep01_main_005",
		ObjectiveId = "obj_ep01_main_005_003",
	},
	interaction_ep01_main_008_005 = {
		InteractionId = "interaction_ep01_main_008_005",
		Type = "QuestObjective",
		ZoneId = "zone_ep01_moon_walk",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Star Core Restoration Point",
		QuestId = "quest_ep01_main_008",
		ObjectiveId = "obj_ep01_main_008_005",
	},
	interaction_disc_ep01_command_star_core_display = {
		InteractionId = "interaction_disc_ep01_command_star_core_display",
		Type = "Discovery",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Discover",
		PromptObjectText = "Star Core Display",
		DiscoveryId = "disc_ep01_command_star_core_display",
	},
	interaction_travel_ep01_universe_explorer = {
		InteractionId = "interaction_travel_ep01_universe_explorer",
		Type = "ZoneTravel",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Travel",
		PromptObjectText = "Universe Explorer",
	},
}
