return {
	interaction_npc_atom_guide = {
		InteractionId = "interaction_npc_atom_guide",
		Type = "NPCGuide",
		VisibilityPolicy = "NPCGuide",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Ask",
		PromptObjectText = "Atom",
		CharacterId = "character_atom",
	},
	interaction_npc_neutron_guide = {
		InteractionId = "interaction_npc_neutron_guide",
		Type = "NPCGuide",
		VisibilityPolicy = "NPCGuide",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Ask",
		PromptObjectText = "Neutron",
		CharacterId = "character_neutron",
	},
	interaction_npc_proton_guide = {
		InteractionId = "interaction_npc_proton_guide",
		Type = "NPCGuide",
		VisibilityPolicy = "NPCGuide",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Ask",
		PromptObjectText = "Proton",
		CharacterId = "character_proton",
	},
	interaction_start_ep01_main_001 = {
		InteractionId = "interaction_start_ep01_main_001",
		Type = "QuestStart",
		VisibilityPolicy = "QuestStart",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Start Quest",
		PromptObjectText = "Expedition Launch",
		QuestId = "quest_ep01_main_001",
	},
	interaction_start_ep01_main_002 = {
		InteractionId = "interaction_start_ep01_main_002",
		Type = "QuestStart",
		VisibilityPolicy = "QuestStart",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Start Quest",
		PromptObjectText = "Universe Signal Mission",
		QuestId = "quest_ep01_main_002",
	},
	interaction_complete_ep01_main_001 = {
		InteractionId = "interaction_complete_ep01_main_001",
		Type = "QuestComplete",
		VisibilityPolicy = "QuestComplete",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Complete Quest",
		PromptObjectText = "Complete Quest 001",
		QuestId = "quest_ep01_main_001",
	},
	interaction_ep01_main_001_001 = {
		InteractionId = "interaction_ep01_main_001_001",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Expedition Terminal",
		QuestId = "quest_ep01_main_001",
		ObjectiveId = "obj_ep01_main_001_001",
	},
	interaction_ep01_main_001_002 = {
		InteractionId = "interaction_ep01_main_001_002",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Mission Briefing",
		QuestId = "quest_ep01_main_001",
		ObjectiveId = "obj_ep01_main_001_002",
	},
	interaction_ep01_main_001_003 = {
		InteractionId = "interaction_ep01_main_001_003",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Launch Console",
		QuestId = "quest_ep01_main_001",
		ObjectiveId = "obj_ep01_main_001_003",
	},
	interaction_ep01_main_002_002 = {
		InteractionId = "interaction_ep01_main_002_002",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Signal Marker",
		QuestId = "quest_ep01_main_002",
		ObjectiveId = "obj_ep01_main_002_002",
	},
	interaction_ep01_main_005_003 = {
		InteractionId = "interaction_ep01_main_005_003",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_theos_satellite_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "THEOS Monitor",
		QuestId = "quest_ep01_main_005",
		ObjectiveId = "obj_ep01_main_005_003",
	},
	interaction_ep01_main_008_005 = {
		InteractionId = "interaction_ep01_main_008_005",
		Type = "QuestObjective",
		VisibilityPolicy = "QuestObjective",
		ZoneId = "zone_ep01_moon_walk",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Interact",
		PromptObjectText = "Star Core Restoration Point",
		QuestId = "quest_ep01_main_008",
		ObjectiveId = "obj_ep01_main_008_005",
	},
	interaction_disc_ep01_command_star_core_display = {
		InteractionId = "interaction_disc_ep01_command_star_core_display",
		Type = "Discovery",
		VisibilityPolicy = "Discovery",
		ZoneId = "zone_ep01_command_center",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Inspect",
		PromptObjectText = "Star Core Display",
		DiscoveryId = "disc_ep01_command_star_core_display",
		ObjectiveProgressIds = {
			"obj_ep01_main_001_004",
		},
	},
	interaction_travel_ep01_universe_explorer = {
		InteractionId = "interaction_travel_ep01_universe_explorer",
		Type = "ZoneTravel",
		VisibilityPolicy = "ZoneTravel",
		ZoneId = "zone_ep01_universe_explorer",
		Enabled = true,
		EnabledInWorld = true,
		PromptActionText = "Travel",
		PromptObjectText = "Universe Explorer",
	},
}
