return {
	item_ep01_fragment_universe = {
		ItemId = "item_ep01_fragment_universe",
		Category = "EpisodeFragment",
		Stackable = false,
		Persistent = true,
		FragmentType = "Universe",
		SegmentType = nil,
		ConsumedOnAssembly = false,
	},
	item_ep01_fragment_earth = {
		ItemId = "item_ep01_fragment_earth",
		Category = "EpisodeFragment",
		Stackable = false,
		Persistent = true,
		FragmentType = "Earth",
		SegmentType = nil,
		ConsumedOnAssembly = false,
	},
	item_ep01_fragment_theos = {
		ItemId = "item_ep01_fragment_theos",
		Category = "EpisodeFragment",
		Stackable = false,
		Persistent = true,
		FragmentType = "THEOS",
		SegmentType = nil,
		ConsumedOnAssembly = false,
	},
	item_ep01_fragment_rocket = {
		ItemId = "item_ep01_fragment_rocket",
		Category = "EpisodeFragment",
		Stackable = false,
		Persistent = true,
		FragmentType = "Rocket",
		SegmentType = nil,
		ConsumedOnAssembly = false,
	},
	item_ep01_fragment_moon = {
		ItemId = "item_ep01_fragment_moon",
		Category = "EpisodeFragment",
		Stackable = false,
		Persistent = true,
		FragmentType = "Moon",
		SegmentType = nil,
		ConsumedOnAssembly = false,
	},
	item_star_core_segment_01 = {
		ItemId = "item_star_core_segment_01",
		Category = "StarCoreSegment",
		Stackable = false,
		Persistent = true,
		FragmentType = nil,
		SegmentType = "Segment01",
	},
	item_star_core_segment_02 = {
		ItemId = "item_star_core_segment_02",
		Category = "StarCoreSegment",
		Stackable = false,
		Persistent = true,
		FragmentType = nil,
		SegmentType = "Segment02",
	},
	item_star_core_segment_03 = {
		ItemId = "item_star_core_segment_03",
		Category = "StarCoreSegment",
		Stackable = false,
		Persistent = true,
		FragmentType = nil,
		SegmentType = "Segment03",
	},
	item_star_core_segment_04 = {
		ItemId = "item_star_core_segment_04",
		Category = "StarCoreSegment",
		Stackable = false,
		Persistent = true,
		FragmentType = nil,
		SegmentType = "Segment04",
	},
	item_star_core_segment_05 = {
		ItemId = "item_star_core_segment_05",
		Category = "StarCoreSegment",
		Stackable = false,
		Persistent = true,
		FragmentType = nil,
		SegmentType = "Segment05",
	},
}
