return {
	journal_ep01_expedition_started = {
		JournalEntryId = "journal_ep01_expedition_started",
		UnlockSourceType = "Quest",
		UnlockSourceId = "quest_ep01_main_001",
		Category = "Episode",
	},
	journal_ep01_star_core_segment_status = {
		JournalEntryId = "journal_ep01_star_core_segment_status",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_command_star_core_display",
		Category = "StarCore",
	},
	journal_ep01_broken_star_signal = {
		JournalEntryId = "journal_ep01_broken_star_signal",
		UnlockSourceType = "Quest",
		UnlockSourceId = "quest_ep01_main_002",
		Category = "Quest",
	},
	journal_ep01_fragment_universe = {
		JournalEntryId = "journal_ep01_fragment_universe",
		UnlockSourceType = "Item",
		UnlockSourceId = "item_ep01_fragment_universe",
		Category = "Fragment",
	},
	journal_ep01_fragment_earth = {
		JournalEntryId = "journal_ep01_fragment_earth",
		UnlockSourceType = "Item",
		UnlockSourceId = "item_ep01_fragment_earth",
		Category = "Fragment",
	},
	journal_ep01_fragment_theos = {
		JournalEntryId = "journal_ep01_fragment_theos",
		UnlockSourceType = "Item",
		UnlockSourceId = "item_ep01_fragment_theos",
		Category = "Fragment",
	},
	journal_ep01_fragment_rocket = {
		JournalEntryId = "journal_ep01_fragment_rocket",
		UnlockSourceType = "Item",
		UnlockSourceId = "item_ep01_fragment_rocket",
		Category = "Fragment",
	},
	journal_ep01_astronaut_readiness = {
		JournalEntryId = "journal_ep01_astronaut_readiness",
		UnlockSourceType = "Quest",
		UnlockSourceId = "quest_ep01_main_007",
		Category = "Badge",
	},
	journal_ep01_fragment_moon = {
		JournalEntryId = "journal_ep01_fragment_moon",
		UnlockSourceType = "Item",
		UnlockSourceId = "item_ep01_fragment_moon",
		Category = "Fragment",
	},
	journal_ep01_star_core_segment_01_restored = {
		JournalEntryId = "journal_ep01_star_core_segment_01_restored",
		UnlockSourceType = "Item",
		UnlockSourceId = "item_star_core_segment_01",
		Category = "StarCore",
	},
	journal_ep01_episode_complete = {
		JournalEntryId = "journal_ep01_episode_complete",
		UnlockSourceType = "Episode",
		UnlockSourceId = "ep01_lost_star_core",
		Category = "Episode",
	},
	journal_ep01_theos_satellite_history = {
		JournalEntryId = "journal_ep01_theos_satellite_history",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_theos_satellite_history",
		Category = "Lore",
	},
	journal_ep01_theos_theos_1 = {
		JournalEntryId = "journal_ep01_theos_theos_1",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_theos_theos_1",
		Category = "Lore",
	},
	journal_ep01_theos_theos_2 = {
		JournalEntryId = "journal_ep01_theos_theos_2",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_theos_theos_2",
		Category = "Lore",
	},
	journal_ep01_theos_thailand_map = {
		JournalEntryId = "journal_ep01_theos_thailand_map",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_theos_thailand_map",
		Category = "Lore",
	},
	journal_ep01_theos_satellite_imagery = {
		JournalEntryId = "journal_ep01_theos_satellite_imagery",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_theos_satellite_imagery",
		Category = "Lore",
	},
	journal_ep01_theos_flood_monitoring = {
		JournalEntryId = "journal_ep01_theos_flood_monitoring",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_theos_disaster_monitoring",
		Category = "Lore",
	},
	journal_ep01_theos_agriculture_monitoring = {
		JournalEntryId = "journal_ep01_theos_agriculture_monitoring",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_theos_agriculture_monitoring",
		Category = "Lore",
	},
	journal_ep01_theos_water_resource_monitoring = {
		JournalEntryId = "journal_ep01_theos_water_resource_monitoring",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_theos_water_resource_monitoring",
		Category = "Lore",
	},
	journal_ep01_theos_forest_monitoring = {
		JournalEntryId = "journal_ep01_theos_forest_monitoring",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_theos_forest_monitoring",
		Category = "Lore",
	},
	journal_ep01_hidden_space_inspirium_secret = {
		JournalEntryId = "journal_ep01_hidden_space_inspirium_secret",
		UnlockSourceType = "Discovery",
		UnlockSourceId = "disc_ep01_hidden_space_inspirium_secret",
		Category = "Secret",
	},
}
