return {
	reward_ep01_main_001 = {
		RewardBundleId = "reward_ep01_main_001",
		ExplorerScore = 125,
		Items = {},
		Badges = {},
		UnlockZones = { "zone_ep01_universe_explorer" },
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_expedition_started", "journal_ep01_star_core_segment_status" },
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerQuestCompletion",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_main_002 = {
		RewardBundleId = "reward_ep01_main_002",
		ExplorerScore = 150,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_broken_star_signal" },
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerQuestCompletion",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_main_003 = {
		RewardBundleId = "reward_ep01_main_003",
		ExplorerScore = 150,
		Items = { { ItemId = "item_ep01_fragment_universe", Quantity = 1 } },
		Badges = {},
		UnlockZones = { "zone_ep01_terrain_sandbox" },
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_fragment_universe" },
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerQuestCompletion",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_main_004 = {
		RewardBundleId = "reward_ep01_main_004",
		ExplorerScore = 175,
		Items = { { ItemId = "item_ep01_fragment_earth", Quantity = 1 } },
		Badges = {},
		UnlockZones = { "zone_ep01_theos_satellite_center" },
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_fragment_earth" },
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerQuestCompletion",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_main_005 = {
		RewardBundleId = "reward_ep01_main_005",
		ExplorerScore = 175,
		Items = { { ItemId = "item_ep01_fragment_theos", Quantity = 1 } },
		Badges = {},
		UnlockZones = { "zone_ep01_rocket_mission" },
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_fragment_theos" },
		LoreUnlocks = { "lore_ep01_theos_calibration_console", "lore_ep01_theos_fragment" },
		DuplicatePolicy = "OncePerPlayerPerQuestCompletion",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_main_006 = {
		RewardBundleId = "reward_ep01_main_006",
		ExplorerScore = 175,
		Items = { { ItemId = "item_ep01_fragment_rocket", Quantity = 1 } },
		Badges = {},
		UnlockZones = { "zone_ep01_astronaut_training" },
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_fragment_rocket" },
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerQuestCompletion",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_main_007 = {
		RewardBundleId = "reward_ep01_main_007",
		ExplorerScore = 150,
		Items = {},
		Badges = { "badge_ep01_astronaut" },
		UnlockZones = { "zone_ep01_moon_walk" },
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_astronaut_readiness" },
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerQuestCompletion",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_main_008 = {
		RewardBundleId = "reward_ep01_main_008",
		ExplorerScore = 250,
		Items = {
			{ ItemId = "item_ep01_fragment_moon", Quantity = 1 },
			{ ItemId = "item_star_core_segment_01", Quantity = 1 },
		},
		Badges = { "badge_ep01_explorer", "badge_ep01_space_pioneer" },
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = {
			"journal_ep01_fragment_moon",
			"journal_ep01_star_core_segment_01_restored",
			"journal_ep01_episode_complete",
		},
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerQuestCompletionAndAssemblyValidation",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_optional_005_satellite_imagery = {
		RewardBundleId = "reward_ep01_optional_005_satellite_imagery",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_theos_satellite_imagery" },
		LoreUnlocks = { "lore_ep01_theos_satellite_imagery" },
		DuplicatePolicy = "OncePerPlayerPerOptionalObjective",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_optional_005_flood_monitoring = {
		RewardBundleId = "reward_ep01_optional_005_flood_monitoring",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_theos_flood_monitoring" },
		LoreUnlocks = { "lore_ep01_theos_disaster_monitoring" },
		DuplicatePolicy = "OncePerPlayerPerOptionalObjective",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_optional_005_agriculture_monitoring = {
		RewardBundleId = "reward_ep01_optional_005_agriculture_monitoring",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_theos_agriculture_monitoring" },
		LoreUnlocks = { "lore_ep01_theos_agriculture_monitoring" },
		DuplicatePolicy = "OncePerPlayerPerOptionalObjective",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_hidden_space_inspirium_secret = {
		RewardBundleId = "reward_ep01_hidden_space_inspirium_secret",
		ExplorerScore = 100,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_hidden_space_inspirium_secret" },
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerHiddenDiscovery",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_discovery_theos_satellite_history = {
		RewardBundleId = "reward_ep01_discovery_theos_satellite_history",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_theos_satellite_history" },
		LoreUnlocks = { "lore_ep01_theos_satellite_history" },
		DuplicatePolicy = "OncePerPlayerPerDiscovery",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_discovery_theos_theos_1 = {
		RewardBundleId = "reward_ep01_discovery_theos_theos_1",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_theos_theos_1" },
		LoreUnlocks = { "lore_ep01_theos_theos_1" },
		DuplicatePolicy = "OncePerPlayerPerDiscovery",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_discovery_theos_theos_2 = {
		RewardBundleId = "reward_ep01_discovery_theos_theos_2",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_theos_theos_2" },
		LoreUnlocks = { "lore_ep01_theos_theos_2" },
		DuplicatePolicy = "OncePerPlayerPerDiscovery",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_discovery_theos_thailand_map = {
		RewardBundleId = "reward_ep01_discovery_theos_thailand_map",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_theos_thailand_map" },
		LoreUnlocks = { "lore_ep01_theos_thailand_map" },
		DuplicatePolicy = "OncePerPlayerPerDiscovery",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_discovery_theos_water_resource_monitoring = {
		RewardBundleId = "reward_ep01_discovery_theos_water_resource_monitoring",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_theos_water_resource_monitoring" },
		LoreUnlocks = { "lore_ep01_theos_water_resource_monitoring" },
		DuplicatePolicy = "OncePerPlayerPerDiscovery",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_discovery_theos_forest_monitoring = {
		RewardBundleId = "reward_ep01_discovery_theos_forest_monitoring",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = { "journal_ep01_theos_forest_monitoring" },
		LoreUnlocks = { "lore_ep01_theos_forest_monitoring" },
		DuplicatePolicy = "OncePerPlayerPerDiscovery",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_teamwork_main_001 = {
		RewardBundleId = "reward_ep01_teamwork_main_001",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = {},
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerEligibleQuestTeamworkContribution",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_teamwork_main_002 = {
		RewardBundleId = "reward_ep01_teamwork_main_002",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = {},
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerEligibleQuestTeamworkContribution",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_teamwork_main_003 = {
		RewardBundleId = "reward_ep01_teamwork_main_003",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = {},
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerEligibleQuestTeamworkContribution",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_teamwork_main_004 = {
		RewardBundleId = "reward_ep01_teamwork_main_004",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = {},
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerEligibleQuestTeamworkContribution",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_teamwork_main_005 = {
		RewardBundleId = "reward_ep01_teamwork_main_005",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = {},
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerEligibleQuestTeamworkContribution",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_teamwork_main_006 = {
		RewardBundleId = "reward_ep01_teamwork_main_006",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = {},
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerEligibleQuestTeamworkContribution",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_teamwork_main_007 = {
		RewardBundleId = "reward_ep01_teamwork_main_007",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = {},
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerEligibleQuestTeamworkContribution",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
	reward_ep01_teamwork_main_008 = {
		RewardBundleId = "reward_ep01_teamwork_main_008",
		ExplorerScore = 25,
		Items = {},
		Badges = {},
		UnlockZones = {},
		UnlockEpisodes = {},
		JournalUnlocks = {},
		LoreUnlocks = {},
		DuplicatePolicy = "OncePerPlayerPerEligibleQuestTeamworkContribution",
		GrantService = "RewardService",
		ConsumesItems = {},
	},
}
